# Generated by Django 4.2.2 on 2023-06-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_course_language_delete_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='ourse',
            new_name='course',
        ),
    ]
