# Generated by Django 4.2.2 on 2023-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_course_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Certificate',
            field=models.BooleanField(max_length=100, null=True),
        ),
    ]
