# Generated by Django 4.2.2 on 2023-06-20 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_usercourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourse',
            new_name='UserCource',
        ),
    ]
