# Generated by Django 3.2.9 on 2023-07-02 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_language_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
